---
title: "Vuelos"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r setup}
library(tidyverse)
library(lubridate)
library(datos)
```
 
```{r vuelos}
vuelos %>% 
  select(anio, mes, dia, hora, minuto) %>% 
  mutate(salida = make_datetime(anio, mes, dia, hora, minuto))
```
```{r vuelos_dt}
hacer_fechahora_100 <- function(anio, mes, dia, tiempo) {
  make_datetime(anio, mes, dia, tiempo %/% 100, tiempo %% 100)
}

vuelos_dt <- vuelos %>% 
  filter(!is.na(horario_salida), !is.na(horario_llegada)) %>%
  mutate(horario_salida = hacer_fechahora_100( anio, mes, dia, horario_salida),
        horario_llegada = hacer_fechahora_100(anio, mes, dia, horario_llegada),
        llegada_programada =  hacer_fechahora_100(anio, mes, dia, llegada_programada),
         salida_programada =  hacer_fechahora_100(anio, mes, dia, salida_programada),
         ) %>% 
  select(origen, destino, starts_with("atraso"), starts_with("horario"), ends_with("programada"), tiempo_vuelo)
```

```{r freq_fechasalida}
vuelos_dt %>% 
  ggplot(aes(horario_salida)) +
  geom_freqpoly(binwidth = 86400) #86400 segundos = 1 día
```

```{r freq_salida_20130102}
vuelos_dt %>% 
  filter(horario_salida < ymd("2013-01-02")) %>% 
  ggplot(aes(horario_salida)) +
  geom_freqpoly(binwidth = 600) # 600seg = 10 min
```
```{r }
vuelos_dt %>% 
  mutate(dia_semana = wday(horario_salida, label = TRUE)) %>% 
  ggplot(aes(dia_semana)) +
  geom_bar()
```

```{r demora}
# segun horario de salida
en_horario_salida <- vuelos_dt %>% 
  mutate(minuto = minute(horario_salida)) %>% 
  group_by(minuto) %>% 
  summarise(atraso_promedio = mean(atraso_salida, na.rm = TRUE),
            n = n())
en_horario_salida %>% 
  ggplot(aes(minuto, atraso_promedio)) +
  geom_line()

# segun salida_programada

en_salida_programada <- vuelos_dt %>% 
  mutate(minuto = minute(salida_programada)) %>% 
  group_by(minuto) %>% 
  summarise(atraso_promedio = mean(atraso_salida, na.rm = TRUE),
            n = n())

en_salida_programada  %>% 
  ggplot(aes(minuto, atraso_promedio)) +
  geom_line()
```
```{r cant.vuelos en minutos de hora}
en_salida_programada %>% 
  ggplot(aes(minuto, n)) +
  geom_line()
```
```{r redondeo_prueba}

vuelos_redondeo <- vuelos_dt %>%  filter(horario_salida > ymd(20130115)) %>% 
    transmute(horario_salida, piso = floor_date(horario_salida, "week"), dif = ((horario_salida - piso)) , techo = ceiling_date(horario_salida, "week"), redon = round_date(horario_salida, "week")) 
```
```{r redondeo_vuelos}
vuelos_dt %>%
  count(semana = floor_date(horario_salida, "week")) %>%
  ggplot(aes(semana, n)) +
  geom_line()
```


```{r update}
# update(
#   object,
#   ...,
#   roll = FALSE,
#   week_start = getOption("lubridate.week.start", 7),
#   simple = NULL
# )
fechahora <- ymd_hms("2016-07-08 12:34:56")
year(fechahora) <- 2020
month(fechahora) <- 01

#para ver plot de cada dia del año... se puede ir variando el yday..
vuelos_dt %>%
  filter(horario_salida == update(horario_salida, yday = 3)) %>%
  ggplot(aes(horario_salida)) +
  geom_freqpoly(binwidth = 300)

```
Algunos vuelos dicen arribar antes de la salida?
```{r}
vuelos_dt %>% 
  filter(horario_llegada < horario_salida)
```

estos son vuelos nocturos. Para que esto no pase generamos variable nocturno

```{r nocturno}
vuelos_dt <- vuelos_dt %>%
  mutate(
    nocturno = horario_llegada < horario_salida,
    horario_llegada = horario_llegada + days(nocturno * 1),
    llegada_programada = llegada_programada + days(nocturno * 1)
  )
```

